-- Production uchun Projects malumotlari
-- Ishlatish: psql -d cursor_market -f projects_prod.sql

-- Project 13: (nomsiz)
INSERT INTO public.projects (id, name_uz, name_ru, name_en, description_uz, description_ru, description_en, category, subcategory, technologies, features, integrations, color, image_url, video_url, images, status, is_top, is_new, views, favorites, created_at)
VALUES (13, '', '', '', '', '', '', 'Sanoat va Ishlab Chiqarish', 'Ishlab chiqarish monitoringi', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, 'from-[#00a6a6] to-[#00a6a6]/80', '/uploads/images/a64e777e-2351-4ec4-97ee-b778b9ab5b6c.jpg', NULL, '[]'::jsonb, 'ACTIVE', false, false, 10, 0, '2026-01-07T11:55:36.854795+05:00')
ON CONFLICT (id) DO UPDATE SET name_uz=EXCLUDED.name_uz, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, description_uz=EXCLUDED.description_uz, description_ru=EXCLUDED.description_ru, description_en=EXCLUDED.description_en, category=EXCLUDED.category, subcategory=EXCLUDED.subcategory, technologies=EXCLUDED.technologies, features=EXCLUDED.features, integrations=EXCLUDED.integrations, color=EXCLUDED.color, image_url=EXCLUDED.image_url, video_url=EXCLUDED.video_url, images=EXCLUDED.images, status=EXCLUDED.status, is_top=EXCLUDED.is_top, is_new=EXCLUDED.is_new, updated_at=NOW();

-- Project 12: Nonbor - Oshxona Avtomatlashtirish
INSERT INTO public.projects (id, name_uz, name_ru, name_en, description_uz, description_ru, description_en, category, subcategory, technologies, features, integrations, color, image_url, video_url, images, status, is_top, is_new, views, favorites, created_at)
VALUES (12, 'Nonbor - Oshxona Avtomatlashtirish', 'Nonbor - Автоматизация общепита', 'Nonbor - Catering Automation', '<ol><li><span style="font-weight: bold;">Restoran</span>,</li><li>kafe va oshxonalar<a href="https://oiko">https://oiko</a></li><li>uchun to''liq avtomatlashtirish tizimi. <a href="https://nonbor.uz">Buyurtmalarni</a> qabul qilish, oshxona boshqaruvi, hisobotlar va moliyaviy <span style="background-color: rgb(254, 240, 138);">nazorat</span>.</li></ol>', 'Полная система автоматизации для ресторанов, кафе и столовых. Приём заказов, управление кухней, отчёты и финансовый контроль.', 'Complete automation system for restaurants, cafes and canteens. Order management, kitchen control, reports and financial monitoring.', 'Biznes va Avtomatlashtirish', 'CRM tizimlari', '["Python", "FastAPI", "PostgreSQL", "React", "WebSocket"]'::jsonb, '[{"uz": "Onlayn buyurtma qabul qilish", "ru": "Онлайн приём заказов", "en": "Online order acceptance"}, {"uz": "Real-time oshxona monitoring", "ru": "Мониторинг кухни в реальном времени", "en": "Real-time kitchen monitoring"}, {"uz": "Moliyaviy hisobotlar", "ru": "Финансовая отчётность", "en": "Financial reports"}, {"uz": "Inventar nazorati", "ru": "Контроль инвентаря", "en": "Inventory control"}, {"uz": "Xodimlar boshqaruvi", "ru": "Управление персоналом", "en": "Staff management"}]'::jsonb, '[]'::jsonb, 'from-[#00a6a6] to-[#00a6a6]/80', '/uploads/images/8109e63e-5b14-464b-a893-ad65398cd006.png', NULL, '[]'::jsonb, 'ACTIVE', true, false, 162, 0, '2025-12-26T12:24:45.054814+05:00')
ON CONFLICT (id) DO UPDATE SET name_uz=EXCLUDED.name_uz, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, description_uz=EXCLUDED.description_uz, description_ru=EXCLUDED.description_ru, description_en=EXCLUDED.description_en, category=EXCLUDED.category, subcategory=EXCLUDED.subcategory, technologies=EXCLUDED.technologies, features=EXCLUDED.features, integrations=EXCLUDED.integrations, color=EXCLUDED.color, image_url=EXCLUDED.image_url, video_url=EXCLUDED.video_url, images=EXCLUDED.images, status=EXCLUDED.status, is_top=EXCLUDED.is_top, is_new=EXCLUDED.is_new, updated_at=NOW();

-- Project 11: 1C ERP - Korxona Yechimi
INSERT INTO public.projects (id, name_uz, name_ru, name_en, description_uz, description_ru, description_en, category, subcategory, technologies, features, integrations, color, image_url, video_url, images, status, is_top, is_new, views, favorites, created_at)
VALUES (11, '1C ERP - Korxona Yechimi', '1С ERP - Корпоративное решение', '1C ERP - Enterprise Solution', '1C ERP tizimi bilan to''liq integratsiya. Moliyaviy hisobotlar, buxgalteriya, ish haqi hisoblash va korxona resurslarini boshqarish.', 'Полная интеграция с системой 1С ERP. Финансовая отчётность, бухгалтерия, расчёт заработной платы и управление ресурсами предприятия.', 'Full integration with 1C ERP system. Financial reporting, accounting, payroll calculation and enterprise resource management.', 'Biznes va Avtomatlashtirish', 'ERP tizimlari', '["1C", "Python", "PostgreSQL", "REST API", "XML"]'::jsonb, '[{"uz": "Moliyaviy hisobotlar", "ru": "Финансовая отчётность", "en": "Financial reports"}, {"uz": "Inventar sinxronizatsiyasi", "ru": "Синхронизация инвентаря", "en": "Inventory synchronization"}, {"uz": "HR boshqaruvi", "ru": "Управление персоналом", "en": "HR management"}, {"uz": "Ish haqi tizimi", "ru": "Система расчёта зарплаты", "en": "Payroll system"}, {"uz": "Avtomatik hisobotlar", "ru": "Автоматические отчёты", "en": "Automated reports"}]'::jsonb, '["Telegram", "Email"]'::jsonb, 'from-primary-500 to-primary-600', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800', NULL, '[]'::jsonb, 'ACTIVE', false, false, 35, 0, '2025-12-26T00:32:30.427179+05:00')
ON CONFLICT (id) DO UPDATE SET name_uz=EXCLUDED.name_uz, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, description_uz=EXCLUDED.description_uz, description_ru=EXCLUDED.description_ru, description_en=EXCLUDED.description_en, category=EXCLUDED.category, subcategory=EXCLUDED.subcategory, technologies=EXCLUDED.technologies, features=EXCLUDED.features, integrations=EXCLUDED.integrations, color=EXCLUDED.color, image_url=EXCLUDED.image_url, video_url=EXCLUDED.video_url, images=EXCLUDED.images, status=EXCLUDED.status, is_top=EXCLUDED.is_top, is_new=EXCLUDED.is_new, updated_at=NOW();

-- Project 10: AmoCRM Professional Integratsiya
INSERT INTO public.projects (id, name_uz, name_ru, name_en, description_uz, description_ru, description_en, category, subcategory, technologies, features, integrations, color, image_url, video_url, images, status, is_top, is_new, views, favorites, created_at)
VALUES (10, 'AmoCRM Professional Integratsiya', 'AmoCRM Профессиональная интеграция', 'AmoCRM Professional Integration', 'AmoCRM bilan to''liq integratsiya. Avtomatik lead yaratish, savdo voronkasi boshqaruvi, mijozlar bilan munosabatlar.', 'Полная интеграция с AmoCRM. Автоматическое создание лидов, управление воронкой продаж, работа с клиентами.', 'Full AmoCRM integration. Automatic lead creation, sales funnel management, customer relationships.', 'Biznes va Avtomatlashtirish', 'CRM tizimlari', '["Python", "AmoCRM API", "Webhook", "FastAPI", "Redis"]'::jsonb, '[{"uz": "Avtomatik lead yaratish", "ru": "Автоматическое создание лидов", "en": "Automatic lead creation"}, {"uz": "Savdo voronkasi boshqaruvi", "ru": "Управление воронкой продаж", "en": "Sales funnel management"}, {"uz": "Email integratsiyasi", "ru": "Интеграция с email", "en": "Email integration"}, {"uz": "Vazifalarni avtomatlashtirish", "ru": "Автоматизация задач", "en": "Task automation"}, {"uz": "Analitika va hisobotlar", "ru": "Аналитика и отчёты", "en": "Analytics and reports"}]'::jsonb, '["AmoCRM", "Telegram", "Email", "WhatsApp"]'::jsonb, 'from-primary-500 to-primary-600', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800', NULL, '[]'::jsonb, 'ACTIVE', false, false, 12, 0, '2025-12-26T00:32:30.177993+05:00')
ON CONFLICT (id) DO UPDATE SET name_uz=EXCLUDED.name_uz, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, description_uz=EXCLUDED.description_uz, description_ru=EXCLUDED.description_ru, description_en=EXCLUDED.description_en, category=EXCLUDED.category, subcategory=EXCLUDED.subcategory, technologies=EXCLUDED.technologies, features=EXCLUDED.features, integrations=EXCLUDED.integrations, color=EXCLUDED.color, image_url=EXCLUDED.image_url, video_url=EXCLUDED.video_url, images=EXCLUDED.images, status=EXCLUDED.status, is_top=EXCLUDED.is_top, is_new=EXCLUDED.is_new, updated_at=NOW();

-- Project 9: Ombor Boshqaruv Tizimi Pro
INSERT INTO public.projects (id, name_uz, name_ru, name_en, description_uz, description_ru, description_en, category, subcategory, technologies, features, integrations, color, image_url, video_url, images, status, is_top, is_new, views, favorites, created_at)
VALUES (9, 'Ombor Boshqaruv Tizimi Pro', 'Система управления складом Pro', 'Warehouse Management System Pro', 'Zamonaviy ombor boshqaruv tizimi. Real-time inventar nazorati, barcode skanerlash, avtomatik buyurtmalar va keng qamrovli hisobotlar.', 'Современная система управления складом. Контроль инвентаря в реальном времени, сканирование штрих-кодов, автоматические заказы и расширенная отчётность.', 'Modern warehouse management system. Real-time inventory control, barcode scanning, automatic orders and comprehensive reporting.', 'Biznes va Avtomatlashtirish', 'Ombor boshqaruvi', '["Python", "FastAPI", "PostgreSQL", "React Native", "Barcode API"]'::jsonb, '[{"uz": "Real-time inventar nazorati", "ru": "Контроль инвентаря в реальном времени", "en": "Real-time inventory control"}, {"uz": "Avtomatik buyurtmalar", "ru": "Автоматические заказы", "en": "Automatic orders"}, {"uz": "Hisobot va analitika", "ru": "Отчёты и аналитика", "en": "Reports and analytics"}, {"uz": "Mobil ilova", "ru": "Мобильное приложение", "en": "Mobile application"}, {"uz": "Umumiy nazorat", "ru": "Общий контроль", "en": "General control"}]'::jsonb, '["Telegram"]'::jsonb, 'from-primary-500 to-primary-600', 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=800', NULL, '["/uploads/images/59ad4041-0401-4068-bf33-d7f08f6a0c0b.webp", "/uploads/images/ab89cd2e-1092-4051-abc0-49d76dee4c22.jpg"]'::jsonb, 'ACTIVE', false, false, 19, 0, '2025-12-26T00:32:08.664738+05:00')
ON CONFLICT (id) DO UPDATE SET name_uz=EXCLUDED.name_uz, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, description_uz=EXCLUDED.description_uz, description_ru=EXCLUDED.description_ru, description_en=EXCLUDED.description_en, category=EXCLUDED.category, subcategory=EXCLUDED.subcategory, technologies=EXCLUDED.technologies, features=EXCLUDED.features, integrations=EXCLUDED.integrations, color=EXCLUDED.color, image_url=EXCLUDED.image_url, video_url=EXCLUDED.video_url, images=EXCLUDED.images, status=EXCLUDED.status, is_top=EXCLUDED.is_top, is_new=EXCLUDED.is_new, updated_at=NOW();

-- Project 3: Mobil Bank Ilovasi
INSERT INTO public.projects (id, name_uz, name_ru, name_en, description_uz, description_ru, description_en, category, subcategory, technologies, features, integrations, color, image_url, video_url, images, status, is_top, is_new, views, favorites, created_at)
VALUES (3, 'Mobil Bank Ilovasi', 'Мобильное банковское приложение', 'Mobile Banking Application', 'To''liq funksional mobil bank ilovasi. Pul o''tkazmalari, to''lovlar, karta boshqaruvi va kredit arizalari.', 'Полнофункциональное мобильное банковское приложение. Денежные переводы, платежи, управление картами и кредитные заявки.', 'Full-featured mobile banking application. Money transfers, payments, card management and loan applications.', 'Mobil va Veb Ilovalar', 'Mobil ilovalar', '["Flutter", "Dart", "Firebase", "REST API", "Biometric Auth"]'::jsonb, '[{"uz": "Pul o''tkazmalari", "ru": "Денежные переводы", "en": "Money transfers"}, {"uz": "Kommunal to''lovlar", "ru": "Оплата коммунальных услуг", "en": "Utility payments"}, {"uz": "Karta boshqaruvi", "ru": "Управление картами", "en": "Card management"}, {"uz": "Kredit arizalari", "ru": "Кредитные заявки", "en": "Loan applications"}, {"uz": "Biometrik autentifikatsiya", "ru": "Биометрическая аутентификация", "en": "Biometric authentication"}]'::jsonb, '[]'::jsonb, 'from-violet-500 to-purple-500', NULL, NULL, '[]'::jsonb, 'ACTIVE', false, false, 0, 0, '2025-12-25T22:22:06.716489+05:00')
ON CONFLICT (id) DO UPDATE SET name_uz=EXCLUDED.name_uz, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, description_uz=EXCLUDED.description_uz, description_ru=EXCLUDED.description_ru, description_en=EXCLUDED.description_en, category=EXCLUDED.category, subcategory=EXCLUDED.subcategory, technologies=EXCLUDED.technologies, features=EXCLUDED.features, integrations=EXCLUDED.integrations, color=EXCLUDED.color, image_url=EXCLUDED.image_url, video_url=EXCLUDED.video_url, images=EXCLUDED.images, status=EXCLUDED.status, is_top=EXCLUDED.is_top, is_new=EXCLUDED.is_new, updated_at=NOW();

-- Project 2: CRM Dashboard - Mijozlar Boshqaruvi
INSERT INTO public.projects (id, name_uz, name_ru, name_en, description_uz, description_ru, description_en, category, subcategory, technologies, features, integrations, color, image_url, video_url, images, status, is_top, is_new, views, favorites, created_at)
VALUES (2, 'CRM Dashboard - Mijozlar Boshqaruvi', 'CRM Dashboard - Управление клиентами', 'CRM Dashboard - Customer Management', 'Zamonaviy CRM tizimi. Mijozlarni boshqarish, analitika, hisobotlar va jamoa hamkorligi uchun yechim.', 'Современная CRM система. Решение для управления клиентами, аналитики, отчётности и командного взаимодействия.', 'Modern CRM system. Solution for customer management, analytics, reporting and team collaboration.', 'Biznes va Avtomatlashtirish', 'CRM tizimlari', '["React", "TypeScript", "TailwindCSS", "Node.js", "MongoDB"]'::jsonb, '[{"uz": "Mijozlar boshqaruvi", "ru": "Управление клиентами", "en": "Customer management"}, {"uz": "Analitika va statistika", "ru": "Аналитика и статистика", "en": "Analytics and statistics"}, {"uz": "Hisobotlar tizimi", "ru": "Система отчётов", "en": "Reporting system"}, {"uz": "Jamoa hamkorligi", "ru": "Командное взаимодействие", "en": "Team collaboration"}, {"uz": "Email marketing", "ru": "Email маркетинг", "en": "Email marketing"}]'::jsonb, '["Telegram"]'::jsonb, 'from-[#0a2d5c] to-[#0a2d5c]/80', NULL, NULL, '[]'::jsonb, 'ACTIVE', false, false, 9, 0, '2025-12-25T22:22:04.633118+05:00')
ON CONFLICT (id) DO UPDATE SET name_uz=EXCLUDED.name_uz, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, description_uz=EXCLUDED.description_uz, description_ru=EXCLUDED.description_ru, description_en=EXCLUDED.description_en, category=EXCLUDED.category, subcategory=EXCLUDED.subcategory, technologies=EXCLUDED.technologies, features=EXCLUDED.features, integrations=EXCLUDED.integrations, color=EXCLUDED.color, image_url=EXCLUDED.image_url, video_url=EXCLUDED.video_url, images=EXCLUDED.images, status=EXCLUDED.status, is_top=EXCLUDED.is_top, is_new=EXCLUDED.is_new, updated_at=NOW();

-- Sequence yangilash
SELECT setval('projects_id_seq', COALESCE((SELECT MAX(id) FROM public.projects), 1));